### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [vlad397/FastApi#18]
Хорошая работа, все учтено.
1. Предлагаю взять за правило: писать README с инструкцией по разворачиванию и запуску приложения, с указанием URL документации.
2. Запуск приложения у вас осуществляется в docker-compose.yaml, что не оптимально. Лучше в `Dockerfile` или `entrypoint` - тогда приложение станет самостоятельной единицей.
3. В `docker-compose.yml` у вас проброшены наружу порты ES и Redis. Это крайне опасно. Для нужд разработки обычно рассматривают вариант с `docker-compose.dev.yaml` или `override`
4. Вот [это](https://github.com/vlad397/FastApi/blob/eb0e153e552f087e9efb8d20d02124fc88b63d64/fastpapi-solution/src/api/v1/films.py#L13) и [это](https://github.com/vlad397/FastApi/blob/eb0e153e552f087e9efb8d20d02124fc88b63d64/fastpapi-solution/src/api/v1/films.py#L20) (и далее в эндпоинтах жанров и людей) тоже модели и к ним относятся все те же рекомендации: держать их в `models.py` или в другом специальном файле `response_models.py` и использовать `orjson`
5. Текстовые сообщения, отдаваемые пользователю, (`film not found`, `genre not found`) у вас расположены в разных местах кода, если появится задача добавить информативности или изменить текст сообщения, или встанет вопрос про мультиязычность, то придется по всему проекту выискивать и менять. Будет проще справиться с этой задачей, если такие сообщения будут вынесены в отдельное место в виде констант (например).
6. Лишний [импорт](https://github.com/vlad397/FastApi/blob/eb0e153e552f087e9efb8d20d02124fc88b63d64/fastpapi-solution/src/services/base.py#L13). Не используется.
7.  При использовании Redis рекомендуется использовать структурированный ключ из которого понятно, что лежит по этому ключу `<es_index>::<first_key>::<first_value>::<second_key>::<second_value>`, :: в ключе просто для примера - separate symbol может в принципе быть любой. Это важно по следующим причинам:
      - Иногда все таки приходится забегать в редис и смотреть что там лежит.
      - Фильтрация по паттерну
 8. Определитесь с использованием кавычек. У вас и `двойные` и `одинарные` - это не очень плохо, но все же рекомендуется придерживаться чего-то одного.

**Comment by hsh01** [comment]
2, 3  #19

**Comment by vlad397** [comment]
4, 5, 6, 7, 8 через push main, без pull request

**Comment by BigDeepBlue** [comment]
LGTM
